# Joblin — Bulk ESCO Normalization

Normalizes every job title (and optionally skills) in your CSV against the ESCO dataset using `esco_service.py` directly.

**Output columns added to the CSV:**

| Column | Description |
|--------|-------------|
| `esco_title` | Matched ESCO occupation label |
| `esco_uri` | ESCO occupation URI |
| `esco_confidence` | Combined score (60% title + 40% avg skill) |
| `esco_title_score` | Raw title fuzzy match score (0–100) |
| `esco_matched_skills` | Comma-separated matched ESCO skill names |

---
> **Prerequisites:** run from the same directory as `esco_service.py` with `DATABASE_URL` set.

## 0 — Config

In [1]:
CSV_PATH = r"jobs_final.csv"  # <-- update

OUTPUT_PATH = "jobs_normalized.csv" # output CSV with ESCO columns added

DATABASE_URL = "postgresql://postgres:1234@localhost:5432/postgres"  # <-- update

# Fuzzy match thresholds (0-100). Lower = more matches but less accurate.
TITLE_THRESHOLD = 60
SKILL_THRESHOLD = 85

# Set to True to also match skills (slower — skips skills if False)
MATCH_SKILLS = True

## 1 — Imports & environment

In [2]:
import os,re
import sys
import json
import logging

import pandas as pd
from tqdm import tqdm

# Set DATABASE_URL so esco_service.py can connect
os.environ["DATABASE_URL"] = DATABASE_URL

# Import directly from esco_service.py in the project folder
from esco_service import (
    fuzzy_match_title,
    fuzzy_match_skills,
    compute_final_score,
    _ensure_loaded,
)

logging.basicConfig(level=logging.INFO)
print("Imports OK")

Imports OK

## 2 — Pre-load ESCO data
Loads occupations and skill pool from Postgres once and caches them for all rows.

In [3]:
print("Loading ESCO data from Postgres...")
esco_df, skill_pool = _ensure_loaded()
print(f"Occupations loaded : {len(esco_df):,}")
print(f"Unique skills loaded: {len(skill_pool):,}")

Loading ESCO data from Postgres...

INFO:esco_service:Loaded 163 ESCO occupations from Postgres.
INFO:esco_service:Built ESCO skill pool with 543 unique skills.

Occupations loaded : 163
Unique skills loaded: 543

In [14]:
tqdm.pandas()

def extract_skills_from_jd(df: pd.DataFrame, esco_df: pd.DataFrame) -> pd.DataFrame:
    skill_pool: set[str] = set()
    for raw in esco_df["mapped_skills"].dropna():
        for s in raw.split(","):
            s = s.strip().lower()
            if s:
                skill_pool.add(s)

    compiled_skills: list[tuple[str, re.Pattern]] = [
        (skill, re.compile(rf"\b{re.escape(skill)}\b"))
        for skill in skill_pool
    ]

    def match_skills(jd: str) -> str:
        if not isinstance(jd, str):
            return ""
        jd_lower = jd.lower()
        matched = [skill for skill, pattern in compiled_skills if pattern.search(jd_lower)]
        return "|".join(matched)

    # Apply to all job descriptions (overwrite existing new_skills)
    df["new_skills"] = df["job_description"].progress_apply(match_skills)

    return df

In [4]:
df = pd.read_csv(CSV_PATH)
df["job_title"] = df["job_title"].fillna(df["Title"])
df["job_description"] = df["job_description"].fillna(df["Description"])
df["job_description"] = df["job_description"].fillna(df["job_summary"])

C:\Users\Hagar Hisham Mostafa\AppData\Local\Temp\ipykernel_4996\3208641540.py:1: DtypeWarning: Columns (0: job_link, 1: company, 2: employment_type, 3: job_description, 4: job_location, 5: job_title, 6: post_date, 7: shift, 8: site_name, 9: skills, 10: job_level, 11: job_id, 12: country, 13: city, 14: job_type, 15: Source, 16: Title, 17: Company, 18: Location, 19: Keywords Matched, 20: Skills, 21: Date Posted, 22: URL, 23: Description, 24: years_of_experience, 25: keywords, 26: job_salary, 27: job_function, 28: industry, 29: listing_type, 30: emails, 31: company_link, 32: company_addresses, 33: company_num_employees, 34: company_description, 35: company_logo, 36: company_url, 37: new_skills, 38: job_position, 39: job_skills, 40: job_summary, 41: is_tech, 42: esco_title, 43: esco_uri, 44: esco_matched_skills) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CSV_PATH)

In [7]:
# Drop rows where job_description is null and reset index
df.dropna(subset=["job_description"], inplace=True)
df.reset_index(drop=True, inplace=True)

In [11]:
# Drop specified columns and any ESCO-related columns
cols_fixed = ["new_skills", "Title", "Description", "job_summary"]
esco_cols = [c for c in df.columns if c.lower().startswith("esco")]
to_drop = [c for c in cols_fixed + esco_cols if c in df.columns]

df.drop(columns=to_drop, inplace=True)
print(f"Dropped columns ({len(to_drop)}): {to_drop}")
print(f"Remaining columns ({len(df.columns)}): {list(df.columns)}")

Dropped columns (9): ['new_skills', 'Title', 'Description', 'job_summary', 'esco_title', 'esco_uri', 'esco_confidence', 'esco_title_score', 'esco_matched_skills']
Remaining columns (39): ['job_link', 'company', 'employment_type', 'job_description', 'job_location', 'job_title', 'post_date', 'shift', 'site_name', 'skills', 'job_level', 'job_id', 'country', 'city', 'job_type', 'Source', 'Company', 'Location', 'Keywords Matched', 'Skills', 'Date Posted', 'URL', 'years_of_experience', 'keywords', 'job_salary', 'job_function', 'industry', 'listing_type', 'emails', 'company_link', 'company_addresses', 'company_num_employees', 'company_description', 'company_logo', 'company_url', 'Unnamed: 0', 'job_position', 'job_skills', 'is_tech']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 213850 entries, 0 to 213849
Data columns (total 39 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_link               184028 non-null  str
 1   company                184245 non-null  str
 2   employment_type        21770 non-null   str
 3   job_description        213850 non-null  str
 4   job_location           185155 non-null  str
 5   job_title              213848 non-null  str
 6   post_date              96219 non-null   str
 7   shift                  21643 non-null   str
 8   site_name              3490 non-null    str
 9   skills                 52312 non-null   str
 10  job_level              92148 non-null   str
 11  job_id                 41518 non-null   str
 12  country                87666 non-null   str
 13  city                   65666 non-null   str
 14  job_type               117472 non-null  str
 15  Source                 27178 non-null   str
 16  Company                26022 non-null   str
 17  Location               27178 non-null   str
 18  Keywords Matched       27178 non-null   str
 19  Skills                 10078 non-null   str
 20  Date Posted            27036 non-null   str
 21  URL                    27177 non-null   str
 22  years_of_experience    1068 non-null    str
 23  keywords               1068 non-null    str
 24  job_salary             74481 non-null   object
 25  job_function           5 non-null       str
 26  industry               16257 non-null   str
 27  listing_type           34038 non-null   str
 28  emails                 10804 non-null   str
 29  company_link           62258 non-null   str
 30  company_addresses      43036 non-null   str
 31  company_num_employees  43130 non-null   str
 32  company_description    33036 non-null   str
 33  company_logo           233 non-null     str
 34  company_url            232 non-null     str
 35  Unnamed: 0             37774 non-null   float64
 36  job_position           37774 non-null   str
 37  job_skills             37734 non-null   str
 38  is_tech                37774 non-null   object
dtypes: float64(1), object(2), str(36)
memory usage: 63.6+ MB

In [15]:
df = extract_skills_from_jd(df, esco_df)

100%|██████████| 213850/213850 [5:54:12<00:00, 10.06it/s]

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 213850 entries, 0 to 213849
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_link               211205 non-null  str
 1   job_description        213850 non-null  str
 2   job_location           212333 non-null  str
 3   job_title              213848 non-null  str
 4   post_date              123255 non-null  str
 5   job_level              213850 non-null  str
 6   country                87666 non-null   str
 7   city                   65666 non-null   str
 8   job_type               139242 non-null  str
 9   Company                210267 non-null  str
 10  years_of_experience    1068 non-null    str
 11  job_salary             74481 non-null   object
 12  industry               16257 non-null   str
 13  listing_type           34038 non-null   str
 14  emails                 10804 non-null   str
 15  company_link           62258 non-null   str
 16  company_addresses      43036 non-null   str
 17  company_num_employees  43130 non-null   str
 18  company_description    33036 non-null   str
 19  company_logo           233 non-null     str
 20  company_url            232 non-null     str
 21  new_skills             213850 non-null  str
dtypes: object(1), str(21)
memory usage: 35.9+ MB

In [18]:
cols_to_remove = [
    "Unnamed: 0", "job_skills", "is_tech", "keywords",
    "Keywords Matched", "Skills", "skills", "job_id", "Source"
]

existing = [c for c in cols_to_remove if c in df.columns]
if existing:
    df.drop(columns=existing, inplace=True)

print(f"Dropped columns ({len(existing)}): {existing}")
print(f"Remaining columns ({len(df.columns)}): {list(df.columns)}")

Dropped columns (9): ['Unnamed: 0', 'job_skills', 'is_tech', 'keywords', 'Keywords Matched', 'Skills', 'skills', 'job_id', 'Source']
Remaining columns (31): ['job_link', 'company', 'employment_type', 'job_description', 'job_location', 'job_title', 'post_date', 'shift', 'site_name', 'job_level', 'country', 'city', 'job_type', 'Company', 'Location', 'Date Posted', 'URL', 'years_of_experience', 'job_salary', 'job_function', 'industry', 'listing_type', 'emails', 'company_link', 'company_addresses', 'company_num_employees', 'company_description', 'company_logo', 'company_url', 'job_position', 'new_skills']

In [19]:
df["job_link"] = df["job_link"].fillna(df["URL"])
df["Company"] = df["Company"].fillna(df["company"])
df["job_location"] = df["job_location"].fillna(df["Location"])
df.drop(columns=["URL", "company", "Location"], inplace=True)

In [42]:
df["post_date"] = df["post_date"].fillna(df["Date Posted"])

In [51]:
df.drop(columns=["job_level_from_years"], inplace=True, errors="ignore")

In [47]:
df["job_level"].unique()

<StringArray>
[         'unknown',        'mid_level',     'senior_level',
       'management',      'entry_level',           'intern',
        'Associate',       'Mid senior',                nan,
          'Fresher',      'Experienced',      'Entry-Level',
 'Mid-Senior Level',     'Senior-Level',        'Mid-Level',
       'Mid-Senior',           'Senior',           'Junior',
        'Mid-level',             'Lead',      'entry level',
   'not applicable',       'internship']
Length: 23, dtype: str

In [49]:
def _parse_years(raw):
    if pd.isna(raw) or str(raw).strip() == "":
        return None
    s = str(raw).lower().strip()
    s = s.replace("–", "-").replace("—", "-")
    s = re.sub(r"(years?|yrs?|year[s]?|years of experience)", "", s)
    s = s.replace("plus", "+").replace(" ", "")
    # handle "3+", "10+ years"
    m = re.search(r"^(\d+)\+$", s)
    if m:
        return float(m.group(1))
    # handle ranges "3-5", "3-6years"
    if "-" in s:
        parts = [p for p in s.split("-") if p]
        try:
            nums = [float(re.search(r"\d+", p).group()) for p in parts if re.search(r"\d+", p)]
            if len(nums) == 1:
                return nums[0]
            return sum(nums) / len(nums)
        except Exception:
            return None
    # single number
    m = re.search(r"\d+", s)
    return float(m.group()) if m else None

def _years_to_level(years):
    if years is None:
        return None
    if years <= 0.5:
        return "intern"
    if years <= 1:
        return "entry_level"
    if years <= 3:
        return "junior"
    if years <= 5:
        return "mid_level"
    if years <= 8:
        return "senior_level"
    return "management"

# Create mapped column and fill missing job_level values
df["job_level_from_years"] = df["years_of_experience"].apply(_parse_years).apply(_years_to_level)
df["job_level"] = df["job_level"].fillna(df["job_level_from_years"])

# Quick summary
print(df["job_level_from_years"].value_counts(dropna=True).to_string())

job_level_from_years
management      212902
intern             409
mid_level          232
senior_level       224
junior              58
entry_level         25

In [53]:
before = len(df)
df.dropna(subset=["job_title", "job_description", "new_skills"], inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"Dropped {before - len(df)} rows; {len(df)} remaining")

Dropped 2 rows; 213848 remaining

In [54]:
df.to_csv("jobs_final_final_inshallah.csv", index=False)

## 3 — Load & preview CSV

In [7]:
df = pd.read_csv(CSV_PATH)
print(f"Loaded {len(df):,} rows")
df.head(5)

C:\Users\Hagar Hisham Mostafa\AppData\Local\Temp\ipykernel_20236\694990172.py:1: DtypeWarning: Columns (0: job_link, 1: company, 2: employment_type, 3: job_description, 4: job_location, 5: job_title, 6: post_date, 7: shift, 8: site_name, 9: skills, 10: job_level, 11: job_id, 12: country, 13: city, 14: job_type, 15: Source, 16: Title, 17: Company, 18: Location, 19: Keywords Matched, 20: Skills, 21: Date Posted, 22: URL, 23: Description, 24: years_of_experience, 25: keywords, 26: job_salary, 27: job_function, 28: industry, 29: listing_type, 30: emails, 31: company_link, 32: company_addresses, 33: company_num_employees, 34: company_description, 35: company_logo, 36: company_url, 37: new_skills, 38: job_position, 39: job_skills, 40: job_summary, 41: is_tech) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CSV_PATH)

Loaded 216,336 rows

,job_link,company,employment_type,job_description,job_location,job_title,post_date,shift,site_name,skills,...,company_num_employees,company_description,company_logo,company_url,new_skills,Unnamed: 0,job_position,job_skills,job_summary,is_tech
0,https://www.dice.com/jobs/detail/AUTOMATION-TE...,"Digital Intelligence Systems, LLC","C2H Corp-To-Corp, C2H Independent, C2H W2, 3 M...",Looking for Selenium engineers...must have sol...,"Atlanta, GA",AUTOMATION TEST ENGINEER,NaN,Telecommuting not available|Travel not required,NaN,SEE BELOW,...,NaN,NaN,NaN,NaN,sql|unix|jenkins|object oriented programming|s...,NaN,NaN,NaN,NaN,NaN
1,https://www.dice.com/jobs/detail/Information-S...,University of Chicago/IT Services,Full Time,The University of Chicago has a rapidly growin...,"Chicago, IL",Information Security Engineer,NaN,Telecommuting not available|Travel not required,NaN,"linux/unix, network monitoring, incident respo...",...,NaN,NaN,NaN,NaN,unix|linux|python,NaN,NaN,NaN,NaN,NaN
2,https://www.dice.com/jobs/detail/Business-Solu...,"Galaxy Systems, Inc.",Full Time,"GalaxE.SolutionsEvery day, our solutions affec...","Schaumburg, IL",Business Solutions Architect,NaN,Telecommuting not available|Travel not required,NaN,"Enterprise Solutions Architecture, business in...",...,NaN,NaN,NaN,NaN,etl|data warehousing|data analysis|data lakes,NaN,NaN,NaN,NaN,NaN
3,https://www.dice.com/jobs/detail/Java-Develope...,TransTech LLC,Full Time,Java DeveloperFull-time/direct-hireBolingbrook...,"Bolingbrook, IL","Java Developer (mid level)- FT- GREAT culture,...",NaN,Telecommuting not available|Travel not required,NaN,Please see job description,...,NaN,NaN,NaN,NaN,sql|c|unix|linux|oracle|tcp/ip|mysql|java|less...,NaN,NaN,NaN,NaN,NaN
4,https://www.dice.com/jobs/detail/DevOps-Engine...,Matrix Resources,Full Time,Midtown based high tech firm has an immediate ...,"Atlanta, GA",DevOps Engineer,NaN,Telecommuting not available|Travel not required,NaN,"Configuration Management, Developer, Linux, Ma...",...,NaN,NaN,NaN,NaN,ansible|linux|docker|puppet|continuous integra...,NaN,NaN,NaN,NaN,NaN

In [12]:
# Null check
print("Nulls in job_title :", df["job_title"].isna().sum())
print("Nulls in job_skills:", df["new_skills"].isna().sum())

Nulls in job_title : 27179
Nulls in job_skills: 0

## 4 — Skills parser

In [55]:
def parse_skills(raw) -> str:
    """Parse job_skills — handles comma strings, JSON arrays, or plain lists. Returns | delimited string."""
    if pd.isna(raw) or str(raw).strip() == "":
        return ""
    if isinstance(raw, list):
        return "|".join(s.strip() for s in raw if str(s).strip())
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            return "|".join(str(s).strip() for s in parsed if str(s).strip())
    except (json.JSONDecodeError, TypeError):
        pass
    return "|".join(s.strip() for s in str(raw).split(",") if s.strip())

## 5 — Dry run (first 5 rows)

In [56]:
for _, row in df.head(20).iterrows():
    title  = str(row["job_title"]).strip()
    skills = parse_skills(row["new_skills"]) if MATCH_SKILLS else []

    title_match   = fuzzy_match_title(title, threshold=TITLE_THRESHOLD)
    skill_matches = fuzzy_match_skills(skills, threshold=SKILL_THRESHOLD) if skills else []

    if title_match:
        confidence = compute_final_score(title_match["score"], skill_matches)
        print(f"[{confidence:5.1f}] '{title}' → '{title_match['preferred_label']}'")
    else:
        print(f"[  ---] '{title}' → no match")

[ 83.8] 'AUTOMATION TEST ENGINEER' → 'automation controls engineer'
[ 85.0] 'Information Security Engineer' → 'security operations manager'
[ 88.5] 'Business Solutions Architect' → 'solutions architect'
[  ---] 'Java Developer (mid level)- FT- GREAT culture, modern technologies, career growth' → no match
[ 90.0] 'DevOps Engineer' → 'cloud DevOps engineer'
[ 73.7] 'SAP FICO Architect' → 'ICT system architect'
[ 93.3] 'Network Engineer' → 'ICT network engineer'
[ 78.4] 'Sr. Web Application Developer (Cloud Team) - Chicago' → 'mobile application developer'
[ 85.0] 'Front End Developer' → 'IoT developer'
[ 92.6] 'Application Support Engineer' → 'application security engineer'
[ 61.5] 'OpenStack Engineer - 12185' → 'full stack software engineer'
[ 83.0] '9001 Data Security Administrator - Unix & IAM' → 'ICT security administrator'
[ 71.4] 'Software Engineer Manager' → 'hardware engineer'
[ 68.1] 'Sales Engineer - Los Angles' → 'regional sales manager'
[100.0] 'Project Manager' → 'project manager'
[ 91.4] 'Windows System Administrator' → 'Windows administrator'
[ 62.9] 'Test Lead / Test Manager' → 'store manager'
[  ---] 'Principal Application Analyst-Supply Chain Lawson' → no match
[ 83.6] 'Messaging Administrator' → 'Windows administrator'
[ 76.2] 'Java Architect - Denver, CO - Fulltime' → 'enterprise architect'

## 6 — Bulk normalization

In [57]:
results = []
no_match = 0

for _, row in tqdm(df.iterrows(), total=len(df), desc="Normalizing"):
    title  = str(row.get("job_title", "") or "").strip()
    skills = parse_skills(row["new_skills"]) if MATCH_SKILLS else []

    if not title:
        results.append({
            "esco_title":         None,
            "esco_uri":           None,
            "esco_confidence":    0.0,
            "esco_title_score":   0,
            "esco_matched_skills": "",
        })
        no_match += 1
        continue

    title_match   = fuzzy_match_title(title, threshold=TITLE_THRESHOLD)
    skill_matches = fuzzy_match_skills(skills, threshold=SKILL_THRESHOLD) if skills else []

    if title_match:
        results.append({
            "esco_title":          title_match["preferred_label"],
            "esco_uri":            title_match["occupation_uri"],
            "esco_confidence":     compute_final_score(title_match["score"], skill_matches),
            "esco_title_score":    title_match["score"],
            "esco_matched_skills": ", ".join(m["matched_skill"] for m in skill_matches),
        })
    else:
        results.append({
            "esco_title":          None,
            "esco_uri":            None,
            "esco_confidence":     0.0,
            "esco_title_score":    0,
            "esco_matched_skills": "",
        })
        no_match += 1

matched = len(df) - no_match
print(f"\nMatched: {matched:,} / {len(df):,} ({matched/len(df)*100:.1f}%)")
print(f"No match: {no_match:,}")

Normalizing: 100%|██████████| 213848/213848 [2:03:11<00:00, 28.93it/s]

Matched: 146,650 / 213,848 (68.6%)
No match: 67,198

## 7 — Merge results & preview

In [58]:
result_df = pd.DataFrame(results)
df_out = pd.concat([df.reset_index(drop=True), result_df], axis=1)

## 8 — Match quality breakdown

In [ ]:
matched_df = df_out[df_out["esco_title"].notna()]

print(f"Total rows        : {len(df_out):,}")
print(f"Matched           : {len(matched_df):,} ({len(matched_df)/len(df_out)*100:.1f}%)")
print(f"Unmatched         : {len(df_out) - len(matched_df):,}")
print()
print("Confidence distribution:")
bins = [0, 50, 70, 85, 95, 101]
labels = ["0-50 (weak)", "50-70 (fair)", "70-85 (good)", "85-95 (strong)", "95-100 (exact)"]
matched_df = matched_df.copy()
matched_df["band"] = pd.cut(matched_df["esco_confidence"], bins=bins, labels=labels, right=False)
print(matched_df["band"].value_counts().sort_index().to_string())

In [ ]:
# Top 10 most common matched ESCO titles
print("Top 10 matched ESCO occupations:")
print(df_out["esco_title"].value_counts().head(10).to_string())

In [12]:
# Unmatched titles — review to decide whether to lower the threshold
unmatched = df_out[df_out["esco_title"].isna()]["job_title"].value_counts()
print(f"Top 100 unmatched titles (total {len(unmatched)} unique):")
print(unmatched.head(100).to_string())

Top 100 unmatched titles (total 42491 unique):
job_title
Research Scientist Model Engineer, Autonomous Startup                                      267
Senior Network Engineer, Load Balancer Specialist                                          172
Senior Software Engineer, Back End                                                         170
Staff Machine Learning Engineer, Series A                                                  129
Senior Software Engineer, Back End (Go, Java)                                               78
Transit Engineering Business Class Director                                                 75
Lead Analyst Identity Governance and Administration (SailPoint IIQ)                         73
Senior Software Engineer, Backend (Golang)                                                  70
Data Catalog and Lineage Central Governance Analyst                                         62
Experienced Associate, Software Engineer (Python/SQL)                                       62
Software Engineering Graduate with Global Technology Leader                                 61
Data Research Analyst, gt.school (Remote) - $60,000/year USD                                59
Senior Network Engineering Lead - Remote                                                    54
Senior Software Engineer, Technology Consulting                                             53
Senior Software Engineer - Embedded & Desktop Linux Optimisation                            52
Senior Data Engineer, Gigster Network - Chicago                                             52
Senior Lead Engineer- Generative AI Engineering (Remote-Eligible)                           51
Senior Software Engineer, Back End (Golang, AWS)                                            50
Authentication Services Lead Platform Engineer (Active Directory, SSO, AWS)                 50
Data Analyst (Bangkok Based, relocation provided)                                           49
Senior Data Analyst (Product Team) (Bangkok Based, relocation provided)                     49
Senior Lead Software Engineer, Back End                                                     44
Manager, Data Engineering (Python, AWS, Airflow, Snowflake) (Hybrid)                        44
Senior Data Analyst (Flights team, Bangkok-based, Relocation provided)                      42
Director, Software Engineering - Card Core                                                  42
Senior Backend Engineer, Seed Stage Fintech                                                 42
Senior Manager, Machine Learning Engineering                                                41
Robert Half Technology Account Executive CS                                                 39
Data Engineer IV - Max Digital (Data Engineering)                                           38
Director, Software Engineering - Card Payments                                              35
Senior Software Engineer, Financial Platforms (Backend)                                     34
Senior Lead Software Engineer, Front End                                                    34
Contractor - Epic Clarity Data Analyst - Revenue Cycle                                      34
Robert Half Technology Account Executive TS                                                 33
Contractor - Epic Clarity Data Analyst                                                      33
Senior HRIS Analyst (Timekeeping and Payroll)                                               32
Senior Software Engineer, Back End (Go, AWS, Java)                                          31
Senior Software Engineer, Backend (Fraud Decisioning)                                       31
Lead Software Engineer (Java, Node, Golang)                                                 31
Senior Network Engineer with Security Clearance                                             30
Lead Software Engineer, Front End (JavaScript)                                              29
Data Engineer IV - Max Digital (Data Operations)                                            28
Senior Director, Software Engineering - Card Core                                           28
SCADA and Automation Engineer - Senior Level                                                28
Lead Data Engineer (Fintech team) (Bangkok based, relocation provided)                      28
Lead Software Engineer, Back End (Python)                                                   28
College of IT: FT Instructor- Software Engineering (Programming in Angular & Python)        26
Entry Level Data Analyst/Management Consultant - Nationwide (US Based Candidates Only)      25
Senior Marketing Data Analyst                                                               25
Robert Half Technology Senior Recruiter CS                                                  24
Senior Director, Software Engineering - Card Authorizations                                 24
Lead Software Engineer, Back End (Go, AWS, Java)                                            24
Software Engineer, Front-End (Security Foundations)                                         23
Software Engineer, Front-End (Retain and Expand)                                            23
Data Scientist, gt.school (Remote) - $60,000/year USD                                       22
Lead Data Analyst – Marketing Strategy & Analytics (Bangkok-based, relocation provided)     22
Senior Director, Software Engineering - Risk Tech                                           22
Master Data Management - Data/Process Analyst                                               20
Principal Machine Learning Engineer                                                         20
Vibe Coder                                                                                  20
Senior Manager, Software Engineering                                                        20
Manager, Software Engineering, Android                                                      20
Network Security Engineer / Senior Network Security Engineer                                20
Future Opportunity- Data Engineering Consultant                                             19
Senior Software Developer with Security Clearance                                           17
Lead Software Engineer (Remote-Eligible)                                                    17
Systems Engineering Graduate with Global Technology Leader                                  17
Oracle DBA                                                                                  16
Robert Half Technology Technology Recruiter TS                                              16
Senior Software Engineer, Backend (Pay Now & Card)                                          16
Senior Cloud Data Engineer - GBP70,000                                                      16
Power BI Developer - Remote - GBP40,000                                                     16
Publishing Systems Engineer I/II/III                                                        16
DevOps                                                                                      15
Robert Half Technology Technology Recruiter CS                                              15
Senior Software Engineer, Backend (SQL, Python)                                             15
Senior Software Engineer, Back End (Java)                                                   15
Finance Analyst to Senior Financial Analyst                                                 15
Data Analyst - SQL & Power BI - UK-wide                                                     15
ISSO                                                                                        15
Data Scientist/Senior Data Scientist                                                        15
Data Conversion Developer, Senior Associate                                                 15
Senior Data Engineer - up to GBP75k                                                         15
Lead Data Engineer, (Python, Java or Scala)                                                 15
Manager, Information Security Office Consultant (Network Engineering)                       15
Technical Services Lead - Sr. Advanced Software Engineer                                    15
Senior Backend and Cloud Engineer - Machine Learning Infrastructure (Python)                15
Lead Software Engineer, Back End (Remote)                                                   14
Lead Software Engineer, Back End (Java/AWS)                                                 14
Software Engineer - Durable Objects                                                         14
Board Certified Behavior Analyst                                                            14
(Global Oil Gas) Senior Data Scientist Expert                                               14
Senior Java Software Engineer (Onsite)                                                      13
Senior Software Engineer, Back End (Java, Springboot, MySQL)                                13
Senior Software Engineer, Back End (Python, Java)                                           13
Senior Software Engineer - Data Strategy (NYC-Hybrid)                                       13
Software Engineer, Android - Slack (Multiple Levels)                                        13
Senior Lead Software Engineer - Back End                                                    13
Sr. Data Analyst / Medical Coder (Medical Policies/Regulations) - REMOTE in CA              13
Senior Accounting Analyst                                                                   13

## 9 — Save to CSV

In [13]:
df_out.to_csv("jobs_final.csv", index=False)
print(f"Saved {len(df_out):,} rows to 'jobs_final.csv'")

KeyboardInterrupt:

## 10 — Optional: lower threshold for unmatched rows

Re-run only the unmatched rows with a lower threshold (e.g. 65) to catch more titles at the cost of some accuracy.

In [59]:
LOWER_THRESHOLD = 50

unmatched_idx = df_out[df_out["esco_title"].isna()].index
print(f"Re-trying {len(unmatched_idx)} unmatched rows with threshold={LOWER_THRESHOLD}...")

recovered = 0
for idx in tqdm(unmatched_idx, desc="Re-matching"):
    title  = str(df_out.at[idx, "job_title"] or "").strip()
    skills = parse_skills(df_out.at[idx, "new_skills"]) if MATCH_SKILLS else []

    title_match   = fuzzy_match_title(title, threshold=LOWER_THRESHOLD)
    skill_matches = fuzzy_match_skills(skills, threshold=SKILL_THRESHOLD) if skills else []

    if title_match:
        df_out.at[idx, "esco_title"]          = title_match["preferred_label"]
        df_out.at[idx, "esco_uri"]            = title_match["occupation_uri"]
        df_out.at[idx, "esco_confidence"]     = compute_final_score(title_match["score"], skill_matches)
        df_out.at[idx, "esco_title_score"]    = title_match["score"]
        df_out.at[idx, "esco_matched_skills"] = ", ".join(m["matched_skill"] for m in skill_matches)
        recovered += 1

print(f"Recovered {recovered} additional matches.")
print(f"Total matched now: {df_out['esco_title'].notna().sum():,} / {len(df_out):,}")

Re-trying 67198 unmatched rows with threshold=50...

Re-matching: 100%|██████████| 67198/67198 [34:54<00:00, 32.09it/s]

Recovered 47813 additional matches.
Total matched now: 194,463 / 213,848

In [62]:
df_out['esco_title'] = df_out['esco_title'].fillna(df_out['job_title'])

In [63]:
embeddings_data = df_out[["job_title", "new_skills", "job_description", "esco_title"]].copy()
embeddings_data["job_id"] = embeddings_data.index
embeddings_data.head(5)

,job_title,new_skills,job_description,esco_title,job_id
0,AUTOMATION TEST ENGINEER,sql|planning|java|selenium|etl|jenkins|unix|go...,Looking for Selenium engineers...must have sol...,automation controls engineer,0
1,Information Security Engineer,python|linux|incident response|unix,The University of Chicago has a rapidly growin...,security operations manager,1
2,Business Solutions Architect,data warehousing|data analysis|etl|business in...,"GalaxE.SolutionsEvery day, our solutions affec...",solutions architect,2
3,"Java Developer (mid level)- FT- GREAT culture,...",sql|c|oracle|sql server|linux|java|less|unix|t...,Java DeveloperFull-time/direct-hireBolingbrook...,"Java Developer (mid level)- FT- GREAT culture,...",3
4,DevOps Engineer,chef|docker|linux|ansible|microservices|puppet...,Midtown based high tech firm has an immediate ...,cloud DevOps engineer,4

In [64]:
embeddings_data.to_csv("jobs_for_embeddings.csv", index=False)

In [65]:
# Save the updated file with recovered matches
df_out.to_csv("jobs_final_inshallah_with_normal.csv", index=False)
print(f"Updated file saved to 'jobs_final.csv'")

Updated file saved to 'jobs_final.csv'